// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.7.1
// source: grpc/pb/scoreboard.proto

package pb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type UserScore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Points int64  `protobuf:"varint,2,opt,name=points,proto3" json:"points,omitempty"`
}

func (x *UserScore) Reset() {
	*x = UserScore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_pb_scoreboard_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserScore) ProtoMessage() {}

func (x *UserScore) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_scoreboard_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserScore.ProtoReflect.Descriptor instead.
func (*UserScore) Descriptor() ([]byte, []int) {
	return file_grpc_pb_scoreboard_proto_rawDescGZIP(), []int{0}
}

func (x *UserScore) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserScore) GetPoints() int64 {
	if x != nil {
		return x.Points
	}
	return 0
}

type PlayerScoreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Score *UserScore `protobuf:"bytes,1,opt,name=score,proto3" json:"score,omitempty"`
}

func (x *PlayerScoreRequest) Reset() {
	*x = PlayerScoreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_pb_scoreboard_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerScoreRequest) ProtoMessage() {}

func (x *PlayerScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_scoreboard_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerScoreRequest.ProtoReflect.Descriptor instead.
func (*PlayerScoreRequest) Descriptor() ([]byte, []int) {
	return file_grpc_pb_scoreboard_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerScoreRequest) GetScore() *UserScore {
	if x != nil {
		return x.Score
	}
	return nil
}

type PlayerScoreResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rank int64 `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`
}

func (x *PlayerScoreResponse) Reset() {
	*x = PlayerScoreResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_pb_scoreboard_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerScoreResponse) ProtoMessage() {}

func (x *PlayerScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_scoreboard_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerScoreResponse.ProtoReflect.Descriptor instead.
func (*PlayerScoreResponse) Descriptor() ([]byte, []int) {
	return file_grpc_pb_scoreboard_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerScoreResponse) GetRank() int64 {
	if x != nil {
		return x.Rank
	}
	return 0
}

type LeaderboardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageSize int64 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Page     int64 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Period   int64 `protobuf:"varint,4,opt,name=period,proto3" json:"period,omitempty"`
}

func (x *LeaderboardRequest) Reset() {
	*x = LeaderboardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_pb_scoreboard_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaderboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardRequest) ProtoMessage() {}

func (x *LeaderboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_scoreboard_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardRequest.ProtoReflect.Descriptor instead.
func (*LeaderboardRequest) Descriptor() ([]byte, []int) {
	return file_grpc_pb_scoreboard_proto_rawDescGZIP(), []int{3}
}

func (x *LeaderboardRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *LeaderboardRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *LeaderboardRequest) GetPeriod() int64 {
	if x != nil {
		return x.Period
	}
	return 0
}

type LeaderboardScore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Score *UserScore `protobuf:"bytes,1,opt,name=score,proto3" json:"score,omitempty"`
	Rank  int64      `protobuf:"varint,2,opt,name=rank,proto3" json:"rank,omitempty"`
}

func (x *LeaderboardScore) Reset() {
	*x = LeaderboardScore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_pb_scoreboard_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaderboardScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardScore) ProtoMessage() {}

func (x *LeaderboardScore) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_scoreboard_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardScore.ProtoReflect.Descriptor instead.
func (*LeaderboardScore) Descriptor() ([]byte, []int) {
	return file_grpc_pb_scoreboard_proto_rawDescGZIP(), []int{4}
}

func (x *LeaderboardScore) GetScore() *UserScore {
	if x != nil {
		return x.Score
	}
	return nil
}

func (x *LeaderboardScore) GetRank() int64 {
	if x != nil {
		return x.Rank
	}
	return 0
}

type LeaderboardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Score []*LeaderboardScore `protobuf:"bytes,1,rep,name=score,proto3" json:"score,omitempty"`
}

func (x *LeaderboardResponse) Reset() {
	*x = LeaderboardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_pb_scoreboard_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaderboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardResponse) ProtoMessage() {}

func (x *LeaderboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_scoreboard_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardResponse.ProtoReflect.Descriptor instead.
func (*LeaderboardResponse) Descriptor() ([]byte, []int) {
	return file_grpc_pb_scoreboard_proto_rawDescGZIP(), []int{5}
}

func (x *LeaderboardResponse) GetScore() []*LeaderboardScore {
	if x != nil {
		return x.Score
	}
	return nil
}

var File_grpc_pb_scoreboard_proto protoreflect.FileDescriptor

var file_grpc_pb_scoreboard_proto_rawDesc = []byte{
	0x0a, 0x18, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x2f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x62,
	0x6f, 0x61, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63,
	0x22, 0x37, 0x0a, 0x09, 0x55, 0x73, 0x65, 0x72, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x22, 0x3b, 0x0a, 0x12, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x25, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52,
	0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x29, 0x0a, 0x13, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x72, 0x61, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x72, 0x61, 0x6e,
	0x6b, 0x22, 0x5d, 0x0a, 0x12, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x61, 0x72, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x65, 0x72, 0x69,
	0x6f, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64,
	0x22, 0x4d, 0x0a, 0x10, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x53,
	0x63, 0x6f, 0x72, 0x65, 0x12, 0x25, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53,
	0x63, 0x6f, 0x72, 0x65, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72,
	0x61, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x22,
	0x43, 0x0a, 0x13, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4c, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x05, 0x73,
	0x63, 0x6f, 0x72, 0x65, 0x32, 0x9e, 0x01, 0x0a, 0x0a, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x62, 0x6f,
	0x61, 0x72, 0x64, 0x12, 0x47, 0x0a, 0x0a, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x53, 0x63, 0x6f, 0x72,
	0x65, 0x12, 0x18, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53,
	0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x47, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x12, 0x18,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x61, 0x72,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_pb_scoreboard_proto_rawDescOnce sync.Once
	file_grpc_pb_scoreboard_proto_rawDescData = file_grpc_pb_scoreboard_proto_rawDesc
)

func file_grpc_pb_scoreboard_proto_rawDescGZIP() []byte {
	file_grpc_pb_scoreboard_proto_rawDescOnce.Do(func() {
		file_grpc_pb_scoreboard_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_pb_scoreboard_proto_rawDescData)
	})
	return file_grpc_pb_scoreboard_proto_rawDescData
}

var file_grpc_pb_scoreboard_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_grpc_pb_scoreboard_proto_goTypes = []interface{}{
	(*UserScore)(nil),           // 0: grpc.UserScore
	(*PlayerScoreRequest)(nil),  // 1: grpc.PlayerScoreRequest
	(*PlayerScoreResponse)(nil), // 2: grpc.PlayerScoreResponse
	(*LeaderboardRequest)(nil),  // 3: grpc.LeaderboardRequest
	(*LeaderboardScore)(nil),    // 4: grpc.LeaderboardScore
	(*LeaderboardResponse)(nil), // 5: grpc.LeaderboardResponse
}
var file_grpc_pb_scoreboard_proto_depIdxs = []int32{
	0, // 0: grpc.PlayerScoreRequest.score:type_name -> grpc.UserScore
	0, // 1: grpc.LeaderboardScore.score:type_name -> grpc.UserScore
	4, // 2: grpc.LeaderboardResponse.score:type_name -> grpc.LeaderboardScore
	1, // 3: grpc.Scoreboard.StoreScore:input_type -> grpc.PlayerScoreRequest
	3, // 4: grpc.Scoreboard.GetLeaderboard:input_type -> grpc.LeaderboardRequest
	2, // 5: grpc.Scoreboard.StoreScore:output_type -> grpc.PlayerScoreResponse
	5, // 6: grpc.Scoreboard.GetLeaderboard:output_type -> grpc.LeaderboardResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_grpc_pb_scoreboard_proto_init() }
func file_grpc_pb_scoreboard_proto_init() {
	if File_grpc_pb_scoreboard_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_pb_scoreboard_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserScore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_pb_scoreboard_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerScoreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_pb_scoreboard_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerScoreResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_pb_scoreboard_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaderboardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_pb_scoreboard_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaderboardScore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_pb_scoreboard_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaderboardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_pb_scoreboard_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_pb_scoreboard_proto_goTypes,
		DependencyIndexes: file_grpc_pb_scoreboard_proto_depIdxs,
		MessageInfos:      file_grpc_pb_scoreboard_proto_msgTypes,
	}.Build()
	File_grpc_pb_scoreboard_proto = out.File
	file_grpc_pb_scoreboard_proto_rawDesc = nil
	file_grpc_pb_scoreboard_proto_goTypes = nil
	file_grpc_pb_scoreboard_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ScoreboardClient is the client API for Scoreboard service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ScoreboardClient interface {
	StoreScore(ctx context.Context, opts ...grpc.CallOption) (Scoreboard_StoreScoreClient, error)
	GetLeaderboard(ctx context.Context, in *LeaderboardRequest, opts ...grpc.CallOption) (*LeaderboardResponse, error)
}

type scoreboardClient struct {
	cc grpc.ClientConnInterface
}

func NewScoreboardClient(cc grpc.ClientConnInterface) ScoreboardClient {
	return &scoreboardClient{cc}
}

func (c *scoreboardClient) StoreScore(ctx context.Context, opts ...grpc.CallOption) (Scoreboard_StoreScoreClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Scoreboard_serviceDesc.Streams[0], "/grpc.Scoreboard/StoreScore", opts...)
	if err != nil {
		return nil, err
	}
	x := &scoreboardStoreScoreClient{stream}
	return x, nil
}

type Scoreboard_StoreScoreClient interface {
	Send(*PlayerScoreRequest) error
	Recv() (*PlayerScoreResponse, error)
	grpc.ClientStream
}

type scoreboardStoreScoreClient struct {
	grpc.ClientStream
}

func (x *scoreboardStoreScoreClient) Send(m *PlayerScoreRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *scoreboardStoreScoreClient) Recv() (*PlayerScoreResponse, error) {
	m := new(PlayerScoreResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *scoreboardClient) GetLeaderboard(ctx context.Context, in *LeaderboardRequest, opts ...grpc.CallOption) (*LeaderboardResponse, error) {
	out := new(LeaderboardResponse)
	err := c.cc.Invoke(ctx, "/grpc.Scoreboard/GetLeaderboard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScoreboardServer is the server API for Scoreboard service.
type ScoreboardServer interface {
	StoreScore(Scoreboard_StoreScoreServer) error
	GetLeaderboard(context.Context, *LeaderboardRequest) (*LeaderboardResponse, error)
}

// UnimplementedScoreboardServer can be embedded to have forward compatible implementations.
type UnimplementedScoreboardServer struct {
}

func (*UnimplementedScoreboardServer) StoreScore(Scoreboard_StoreScoreServer) error {
	return status.Errorf(codes.Unimplemented, "method StoreScore not implemented")
}
func (*UnimplementedScoreboardServer) GetLeaderboard(context.Context, *LeaderboardRequest) (*LeaderboardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLeaderboard not implemented")
}

func RegisterScoreboardServer(s *grpc.Server, srv ScoreboardServer) {
	s.RegisterService(&_Scoreboard_serviceDesc, srv)
}

func _Scoreboard_StoreScore_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ScoreboardServer).StoreScore(&scoreboardStoreScoreServer{stream})
}

type Scoreboard_StoreScoreServer interface {
	Send(*PlayerScoreResponse) error
	Recv() (*PlayerScoreRequest, error)
	grpc.ServerStream
}

type scoreboardStoreScoreServer struct {
	grpc.ServerStream
}

func (x *scoreboardStoreScoreServer) Send(m *PlayerScoreResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *scoreboardStoreScoreServer) Recv() (*PlayerScoreRequest, error) {
	m := new(PlayerScoreRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Scoreboard_GetLeaderboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaderboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoreboardServer).GetLeaderboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Scoreboard/GetLeaderboard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoreboardServer).GetLeaderboard(ctx, req.(*LeaderboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Scoreboard_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Scoreboard",
	HandlerType: (*ScoreboardServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLeaderboard",
			Handler:    _Scoreboard_GetLeaderboard_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StoreScore",
			Handler:       _Scoreboard_StoreScore_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "grpc/pb/scoreboard.proto",
}
